### ISSUE TITLE
No such file or directory: 'features1.npy'

### ISSUE THREAD

**Issue by zhouzheng1123** [sjtuplayer/few-shot-diffusion#1]
when i run the 'train-whole.py', an error occurs:'No such file or directory: 'features1.npy''. May I know how to solve it？

**Comment by sjtuplayer** [comment]
features1.npy is the extracted features from CLIP model, which is used to calculate the Directional Distribution Consistency Loss. You can employ CLIP model to encode more than 1000 source images as features1.npy and encode the few-shot target images as features2.npy. Note that both features1.npy and features2.npy are num*dim (num is the number of encoded images and dim is the dimension of CLIP features)

**Comment by zhouzheng1123** [comment]
> features1.npy is the extracted features from CLIP model, which is used to calculate the Directional Distribution Consistency Loss. You can employ CLIP model to encode more than 1000 source images as features1.npy and encode the few-shot target images as features2.npy. Note that both features1.npy and features2.npy are num*dim (num is the number of encoded images and dim is the dimension of CLIP features)

Thank you for your answer, but I still don't know how to generate an npy file. Do you have any generated script programs in your code? Can you provide more detailed instructions for generating operations.

**Comment by sjtuplayer** [comment]
The code and readme are updated, you can run feature-extractor.py to encode the images

**Comment by zhouzheng1123** [comment]
> The code and readme are updated, you can run feature-extractor.py to encode the images

Thank you very much. This is a great work, and I have another question. Will the source and target images automatically generate the image after the source image migration style is trained together? I don't see any testing code, but I am currently training the code for the third train stage, which is a bit slow and hasn't generated any images yet.

**Comment by zhouzheng1123** [comment]
> > The code and readme are updated, you can run feature-extractor.py to encode the images
> 
> Thank you very much. This is a great work, and I have another question. Will the source and target images automatically generate the image after the source image migration style is trained together? I don't see any testing code, but I am currently training the code for the third train stage, which is a bit slow and hasn't generated any images yet.

Thank you very much for patiently answering my question. However, when I trained train-whole.py, I set epoch to 1. After training, no style transferred images were generated, only weight pt files. What should I do to generate style transferred images?

**Comment by zhouzheng1123** [comment]
Thank you very much for patiently answering my question. However, when I trained train-whole.py, I set epoch to 1. After training, no style transferred images were generated, only weight files. What should I do to generate style transferred images.

**Comment by sjtuplayer** [comment]
The code for inference will be released with the checkpoints soon, which are currently under preparation. If you want to generate images, you can temporarily use DDIM to sample the images

**Comment by tonia86** [comment]
I am very interested in your work. When will the inference code be updated?

**Comment by sjtuplayer** [comment]
Hi~ Thanks for your attention. The inference code will be updated immediately after CVPR 2024.

**Comment by Jamie-Cheung** [comment]
> The code for inference will be released with the checkpoints soon, which are currently under preparation. If you want to generate images, you can temporarily use DDIM to sample the images

May I ask if you can provide the inference code of DDIM mode, because I am submitting SCI papers recently and need to do a comparison experiment with your method. Hope you can provide, we will cite your paper.

**Comment by sjtuplayer** [comment]
Thanks for your patience. I've just finished the suppl of CVPR24 and I'll release the inference code of DDIM mode and the relevant ckeckpoints before Friday. And may I ask which domains you need the most? I will organize and release the relevant checkpoints first.

**Comment by sjtuplayer** [comment]
The code is updated and some pre-trained models are offered. If you have any problem running the code, please feel free to contact us. (Note: the pre-trained models are newly trained by the updated code. Therefore, the results may be slightly different from those in the paper)

**Comment by sjtuplayer** [comment]
you can just delete this line and train from scratch



---Original---
From: "zhanjie ***@***.***&gt;
Date: Fri, Dec 1, 2023 10:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sjtuplayer/few-shot-diffusion] No such file or directory:'features1.npy' (Issue #1)




  
The code is updated and some pre-trained models are offered. If you have any problem running the code, please feel free to contact us. (Note: the pre-trained models are newly trained by the updated code. Therefore, the results may be slightly different from those in the paper)
  
Thank you for updating some pre-trained models. But when I use "python3 train.py --data_path=path_to_dataset" on my source dataset. It seems that the "train.py"  needs to be load "/home/huteng/DDPM2/checkpoints/481157.pth". Thank you for your further response.

**Comment by sjtuplayer** [comment]
> Thank you for updating some pre-trained models. But when I use "python3 train.py --data_path=path_to_dataset" on my source dataset. It seems that the "train.py" needs to be load "/home/huteng/DDPM2/checkpoints/481157.pth". Thank you for your further response.

You can just delete this line and train it from scratch

**Comment by Jamie-Cheung** [comment]
> > Thank you for updating some pre-trained models. But when I use "python3 train.py --data_path=path_to_dataset" on my source dataset. It seems that the "train.py" needs to be load "/home/huteng/DDPM2/checkpoints/481157.pth". Thank you for your further response.
> 
> You can just delete this line and train it from scratch

For "train-whole.py", how much GPU memory do you use for training. Even though I was using single RTX A6000 (48 G) and a batch size of 1, I still didn't have enough memory for training.

**Comment by Jamie-Cheung** [comment]
> > Thank you for updating some pre-trained models. But when I use "python3 train.py --data_path=path_to_dataset" on my source dataset. It seems that the "train.py" needs to be load "/home/huteng/DDPM2/checkpoints/481157.pth". Thank you for your further response.
> 
> You can just delete this line and train it from scratch

Traceback (most recent call last):
  File "/home/few-shot-diffusion-master/few-shot-diffusion-master/train-whole.py", line 196, in <module>
    sampled_images, sampled_middle_images = diffusion_target.ddim_sample(real_image.shape, sample_step=25,
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sjk/Softwares/miniconda3/envs/torch2.0/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/few-shot-diffusion-master/few-shot-diffusion-master/model/ddpm.py", line 310, in ddim_sample
    down = Resizer(shape, 1 / filter_N).cuda()
           ^^^^^^^
NameError: name 'Resizer' is not defined

An error in ddpm.py. Can you give me some new suggestions? I am looking forward to your reply. Thank you.

**Comment by fikry102** [comment]
> features1.npy is the extracted features from CLIP model, which is used to calculate the Directional Distribution Consistency Loss. You can employ CLIP model to encode more than 1000 source images as features1.npy and encode the few-shot target images as features2.npy. Note that both features1.npy and features2.npy are num*dim (num is the number of encoded images and dim is the dimension of CLIP features)

Is it necessary to encode all the source images from the source dataset? Or just choose 1000 source images randomly?

**Comment by Jamie-Cheung** [comment]
> > features1.npy is the extracted features from CLIP model, which is used to calculate the Directional Distribution Consistency Loss. You can employ CLIP model to encode more than 1000 source images as features1.npy and encode the few-shot target images as features2.npy. Note that both features1.npy and features2.npy are num*dim (num is the number of encoded images and dim is the dimension of CLIP features)
> 
> Is it necessary to encode all the source images from the source dataset? Or just choose 1000 source images randomly?

I only randomly choose partial images.

**Comment by sjtuplayer** [comment]
> > features1.npy is the extracted features from CLIP model, which is used to calculate the Directional Distribution Consistency Loss. You can employ CLIP model to encode more than 1000 source images as features1.npy and encode the few-shot target images as features2.npy. Note that both features1.npy and features2.npy are num*dim (num is the number of encoded images and dim is the dimension of CLIP features)
> 
> Is it necessary to encode all the source images from the source dataset? Or just choose 1000 source images randomly?

Actually, the more images you encode, the more accurate the source-domain center is. We have encoded about 10K-20K source-domain images in our experiments

**Comment by 15634960802** [comment]
我用推理阶段的代码生成的结果只是源数据集的图像加上了噪声，没有生成目标域的图像，这是什么原因啊。

**Comment by boxbox2** [comment]
> 我用推理阶段的代码生成的结果只是源数据集的图像加上了噪声，没有生成目标域的图像，这是什么原因啊。

你可以试试 #11

**Comment by 15634960802** [comment]
> 感谢您更新一些预训练模型。但是当我在我的源数据集上使用“python3 train.py --data_path=path_to_dataset”时。看来 “train.py” 需要加载 “/home/huteng/DDPM2/checkpoints/481157.pth”。感谢您的进一步回复。

你好，我想知道，您是否可以运行的起来这个文件。如果图片是1024*1024 的话，是不是要修改图片的尺寸呢？谢谢您的答复
